project: builder
description: Template for SPAI builder project
thumbnail: https://play.google.com/store/apps/details?id=com.hellomagazine.hellomagazine&hl=es_US
storage:
  - name: data
    type: s3
apis:
  - name: runner
    port: 8011
